### ISSUE TITLE
Demos are broken on 5K displays

### ISSUE THREAD

**Issue by gugurete** [manubb/Leaflet.PixiOverlay#2] opened 2017-07-03 07:38 UTC
The basic demo works in firefox but it is broken in chrome
With chrome, on zoom the shapes will wander of their intended position

<img width="2560" alt="screen shot 2017-07-03 at 17 37 37" src="https://user-images.githubusercontent.com/5728632/27782567-6184458e-6016-11e7-8122-56f570501b74.png">

**Comment by gugurete** [comment] 2017-07-03 07:40
as a matter of fact, all of the demos are working only in firefox.
chrome, safari will not work

**Comment by manubb** [comment] 2017-07-03 08:31
Can you give me more details please:
-precise versions of all browsers
-your computer model and OS version
?
What do you mean by demos do not work? Incorrect positions on zoom?

(Demos were tested on:
-Fedora 25 (Chrome 59, Firefox 54 , Opera 46)
-Chromebook (Chrome OS 58)
-Windows 10 + Chrome
-macOS 10.11 and 10.12  (Safari 10, Chrome 59, Firefox 54, Opera 46)
-iOS  Safari 10.3.2
and everything seems fine.)

**Comment by gugurete** [comment] 2017-07-03 22:16
Hi, I just run another set of tests on CentOS and all looks fine here
 - Chrome Version 59.0.3071.109 (Official Build) (64-bit)
 - Opera 45.0
 - Firefox 54

The rendering is broken only on the latest mac OS X (iMac 2016), with the latest versions of Chrome and Safari.
On Zoom/Pan the shapes have incorrect position as you can see it on the attached screenshot

**Comment by gugurete** [comment] 2017-07-03 22:23
It works on a 3 year old macbook too.
It looks like it is something hardware related on my iMac ? I will have another look this evening

**Comment by gugurete** [comment] 2017-07-04 07:38
Defect caused probably by Open GL driver in my iMac 
(iMac Retina 5K, 27-inch, Late 2015, AMD Radeon R9 M395 2048 MB)

After disabling  hardware acceleration in Chrome, issue is not present any more.

**Comment by manubb** [comment] 2017-07-04 09:04
Could you report here the content of Framebuffer section from http://webglreport.com, please?

**Comment by gugurete** [comment] 2017-07-04 19:57
[WebGL1 Report - Chrome.pdf](https://github.com/manubb/Leaflet.PixiOverlay/files/1122959/WebGL1.Report.-.Chrome.pdf)
[WebGL1 Report - Firefox.pdf](https://github.com/manubb/Leaflet.PixiOverlay/files/1122960/WebGL1.Report.-.Firefox.pdf)
[WebGL2 Report - Chrome.pdf](https://github.com/manubb/Leaflet.PixiOverlay/files/1122961/WebGL2.Report.-.Chrome.pdf)
[WebGL2 Report - Firefox.pdf](https://github.com/manubb/Leaflet.PixiOverlay/files/1122962/WebGL2.Report.-.Firefox.pdf)
<img width="1396" alt="framebuffer1" src="https://user-images.githubusercontent.com/5728632/27841679-c5d01b18-6146-11e7-9a84-f8aeb831b663.png">
<img width="1451" alt="framebuffer2" src="https://user-images.githubusercontent.com/5728632/27841678-c5cf2636-6146-11e7-82f6-b9a7ccb6644b.png">

**Comment by gugurete** [comment] 2017-07-04 22:19
Could it be caused by the 5K retina screen ?

**Comment by manubb** [comment] 2017-07-04 22:40
Maybe this is related to a limit on webgl canvas size. Can you check if the problem is fixed on https://manubb.github.io/Leaflet.PixiOverlay/5k-test.html ?

**Comment by manubb** [comment] 2017-07-05 13:36
All demos should be fixed at least with Chrome. Can you give a try with Safari?

**Comment by gugurete** [comment] 2017-07-07 05:42
yes, it is screen size / retina display dependant
I tested it again on the same iMac with the resolution set lower (3200 x 1800),  and it that case it works.

**Comment by gugurete** [comment] 2017-07-10 07:15
Yes, this works perfectly on all browsers on iMac 5K:  
https://manubb.github.io/Leaflet.PixiOverlay/5k-test.html ?

**Comment by manubb** [comment] 2017-07-11 09:01
This problem should be fixed in version 0.0.6. Closing issue.
@gugurete Thanks for reporting!

**Closed by manubb** 2017-07-11 09:01 UTC
